### ISSUE TITLE
Investigate visor spec (length, materials, etc.)

### ISSUE THREAD

**Issue by afroleft** [DoESLiverpool/covid19#11] opened 2020-03-28 08:15 UTC
Natalia was on a call 8 NHS medical doctors last night, all working across the country. 

When they looked at the designs of the visors they thought that it would be optimal if the visor came down to the bottom of their chins vs stopping at their nose. 

**Why:** extra protection from splashes and aerosols. Also offers some level of protection if we have no masks.

**Comment by amcewen** [comment] 2020-03-28 11:25
That's really helpful.  I don't think we've got a good handle on the visors, tbh - at least I haven't.

At the moment I'm prototyping with ~0.07mm thick polyester sheet, but that's because it's what we've got, not because it's the best option.  We've got ~100 A3 sheets of that, so we'll need to source something else anyway - what should we be looking for?

It'd be good if someone can do some reading up on the [slack channels or write-ups of any of the designs](https://github.com/DoESLiverpool/covid19#other-info-links-etc) and then summarize the visor details here.

I think we'd be looking for details on materials used, and their thicknesses, size, and whether it's something that's been okayed by any health services anywhere (to give an idea of where it is on the spectrum from a maker's "I used this" or a medical professional's "this is what we want")

The laser-cut polyprop and 3D printed designs were using use a standard hole-punch design for how the visor attaches (in case that's useful when looking at other designs)

**Comment by LaurieJ** [comment] 2020-03-28 11:46
I wrote up some of the face shield work at helpfulengineering.org  https://docs.google.com/document/d/1r2lhocsvS-GoaCkOWk85nOZ8eMTTneZAisTUCuYR-X0/edit# now 36h out of date, will update with latest from slacks this weekend...

**Comment by ajlennon** [comment] 2020-03-28 14:12
Hi @LaurieJ fwiw Max Zadow and I put a project application into Helpful Engineering for wave #2 on Friday morning. Hoping to hear back from them.

Are  you guys also engaged over at covid-19volunteersuk.slack.com ? They seem more UK based and I see they are setting up regional channels

**Comment by ajlennon** [comment] 2020-03-28 14:13
This was _very_ last minute but some of the information we put in this application may be useful as to where our thinking is going

https://docs.google.com/document/d/1edP_js_qHgL57S_6JvaYwVUFfh2x-DbDntAcT4gygls/edit

**Comment by LaurieJ** [comment] 2020-03-28 14:15
> 
> Are you guys also engaged over at covid-19volunteersuk.slack.com ? They seem more UK based and I see they are setting up regional channels

I would be if my request to join was confirmed :) Waiting quite a while now...

**Comment by ajlennon** [comment] 2020-03-28 14:18
Gotcha I put an invite in the readme which should last a week

https://github.com/DoESLiverpool/covid19

This is the one

https://join.slack.com/t/helpfulengineering/shared_invite/zt-d6ytoynb-_tJjyC7oEd4fT8L0I8ug8Q

**Comment by LaurieJ** [comment] 2020-03-28 15:45
I'm in HelpfulEngineering but not the covid19volunteersUK one...

**Comment by ajlennon** [comment] 2020-03-28 15:47
Ah sorry wrong one -

https://covid-19volunteersuk.slack.com/join/shared_invite/zt-czz3p6vp-6zyuIcrbZBIJw1LdiTbffw

**Comment by amcewen** [comment] 2020-03-28 18:26
We've got some more materials here that we can prototype with.  @KarlDunkerley dropped off a bit (~30cm x ~1m maybe) of clear 1mm thick PETG (which laser-cuts okay, but generates a fair bit of residue you'd need to clean off), and a roll of 1.3m x 30m of 220 micron thick clear polypropylene.  Plus Yangshuo was in fixing something and has shared some thicker unknown material OHP transparency sheets that he's got.

**Comment by ajlennon** [comment] 2020-03-28 21:50
Here's some information I had through from a nurse @Animation1138 on Twitter with some pics of what they currently use

>Hi Alex. Have you tried your designs with glasses wearers. The visors we currently have a 2 ish elastic band that goes around the head.and a sponge on the forehead that keeps them away from your face. I have worn these for 3 thirteen hour shifts and they are good.

![image](https://user-images.githubusercontent.com/1537834/77834617-f2487500-713d-11ea-9018-10a2ba0470ae.png)

![image](https://user-images.githubusercontent.com/1537834/77834620-f6749280-713d-11ea-8d38-4a76f39400a2.png)

![image](https://user-images.githubusercontent.com/1537834/77834626-fbd1dd00-713d-11ea-83ae-bb6fe22892dd.png)

(She sent a video too but I can't work out how to forward it from Twitter - will try to get another copy)

**Comment by ajlennon** [comment] 2020-03-28 21:59
Idea from @andygoodman on a stampable design

![image](https://user-images.githubusercontent.com/1537834/77834815-69cad400-713f-11ea-921a-cdf113faa643.png)

ref: https://twitter.com/wyn_griffith/status/1243980278915379201?s=20

**Comment by andygoodman** [comment] 2020-03-28 22:27
Via Zalli, Holyhead High School, from somewhere else (I’m not aware of originator); stamping discussion with John Story; I just combined.

**Comment by JackiePease** [comment] 2020-03-29 16:40
We've tried the slightly thicker acetate (0.1mm v 0.7mm) - no apparent difference.
I laser cut shields from 220 micron PP (settings 140 speed, 70 power on Gerald). Output would need a cleaning step.  Sturdier and seem to work better with @amcewen laser design, the extra weight counteracts the lifting effect. Also good with Prusa and Spanish designs. DIdn't hold at all on the Verkstan - the nubs on the Spanish design are larger and have "mushroom head" shape.

**Comment by ajlennon** [comment] 2020-03-29 16:46
Hi @JackiePease - I am being asked what materials we need. Can you let me know what we think we need in terms of the usable range of polypropylene sheets and the widths / material for visors?

Thanks!

**Comment by KarlDunkerley** [comment] 2020-03-29 16:56
I'm working on MkIII substituting the velcro with staples. Velcro terrible to work with. Slow.

Seems to work fine. Lots easier but my small stapler a pain so have ordered an £8 proper desktop one with some reach to do the foam. 

Trimming corners with nail clippers. Works fine. Have ordered some heavy duty clippers for £3.

Hopefully 25mm elastic arriving tomorrow.

Have found a source of A4 acetates. 20p each. Easier than cutting roll down and no lasering means no concern over cutting or fumes etc.

Still using laser to cut foams. 10 mins to laser 14 or 42 secs each on 1 pass.

Total cost at moment around 35p each.

**Comment by KarlDunkerley** [comment] 2020-03-29 17:02
Spoke to my newly qualified nurse friend Bev. 

She loves the one I dropped off yesterday.

Her paramedic wife Paula reckons they would be good on the vans as well except when driving though I went down the M57 in one yesterday and had no probs. Probably not a good idea at night though!

Also had long chat with nurse in Scotland I came across on a laser forum. She's working with former colleagues in Yorkshire to get these made. Am sending her a sample.

One thing we discussed was the length as some nurses are petite (so are Bev and Paula). I pointed out that I was using nail clippers so anyone could use scissors to shorten or shape their visor. thicker material would be difficult. You can also use permanent marker to keep to your own.

**Comment by KarlDunkerley** [comment] 2020-03-29 17:07
As for washing, the sheets cut from the PP roll were full of dust. 

Put them in a bowl of luke warm water with a couple of squirts of handwash (anti-bacterial) and then rinsed them. Dried with a teatowel.

Came out v clean. From packets of A4 I am not sure this would be needed if sterile gloves used. No sticky velcro means fully gloved operation possible.

In a production environment, I'd use three bowls of soapy water, clean water and finally alcohol. There may be a fight over the last one. 

Getting there.

**Comment by ajlennon** [comment] 2020-03-29 17:18
@KarlDunkerley - we're being asked for details on what consumables we need. I think we're on top of progressing the 3D print and laser cut designs but you're the man leading the foam-no cut designs. Can you give us specifics on the consumables you need for your design so we can get those details out there?

**Comment by ajlennon** [comment] 2020-03-29 17:19
Details will go in here under the foam section when we are clear on what we need - https://github.com/DoESLiverpool/covid19/issues/21

**Comment by ajlennon** [comment] 2020-03-29 17:20
I'd also like to catch up with you to add your design specifics / instructions etc. to the FaceShield page here - https://github.com/DoESLiverpool/covid19/blob/master/FaceShield.md

We'll add into the No cut foam table

**Comment by ajlennon** [comment] 2020-03-30 11:01
Got this through from @AlyssaAlabassi

> Found this article, may be of guidance. Conclusion is interesting as is the table https://ncbi.nlm.nih.gov/pmc/articles/PMC5015006/
> 
> Table 1
> Advantages and disadvantages of face shields compared with other forms of face/eye protection (i.e., protective facemasks [filtering facepiece respirators, medical/surgical masks], goggles, safety glasses).[11, 12, 16, 19, 21, 22, 38–44]
> 
> Advantages
> more comfortable
> 
> protect a larger portion of the face
> 
> less retained dermal facial heat
> 
> less fogging than goggles
> 
> less claustrophobic
> 
> no impact on breathing resistance
> 
> no fit testing required
> 
> can be disinfected easily
> 
> wearers do not need to be clean shaven
> 
> easy to don and doff
> 
> relatively inexpensive
> 
> no impact on vocalization
> 
> can be worn concurrent to other face/eye PPE
> 
> do not impede facial nonverbal communication
> 
> reduced patient anxiety
> 
> protects against self-inoculation over a wider facial area
> 
> may extend the useful life of a protective facemask when used concurrently
> 
> Disadvantages
> glare
> 
> fogging
> 
> optically imperfect
> 
> Disadvantages
> glare
> 
> fogging
> 
> optically imperfect
> 
> some models may not fit properly over some respirators (e.g., duckbill filtering facepiecerespirators)
> 
> bulkier than goggles and safety glasses
> 
> peripheral fit poorer than protective facemasks

**Comment by KarlDunkerley** [comment] 2020-03-30 11:04
So far not alot of glare for user. Very little fogging. Optically pretty good - reading and driving fine.

**Comment by ajlennon** [comment] 2020-03-30 12:08
Current advice given to medical practitioners as of 30th March @ 1pm h/t  @AlyssaAlabassi

> This is the guidance we just got: A message sent on behalf of the COVID-19 command centre
>  
> Please see attached letter dated 28 March 2020 on Personal Protective Equipment (PPE) which has been jointly signed by NHSI/E, the Academy of the Medical Royal Colleges and Public Health England which confirms current PPE guidance:
>  
> PPE for high-risk procedures:
> Recommended PPE to be used by healthcare workers delivering or assisting with an aerosol generating procedure including in Intensive Care Units or the hot zone of an Emergency Department:
> FFP3 respirator
> long sleeved disposable gown
> gloves
> eye protection (disposable goggles or full-face visor).
>  
> PPE for other settings:
> Recommended PPE to be used by healthcare workers within one metre of a patient with possible or confirmed COVID-19 including staff working in hospitals, primary care, ambulance trusts, community care settings, care homes:
> fluid repellent facemask
> apron
> gloves
> eye protection if there is a risk of splashing or exposure to respiratory droplets.

**Comment by ajlennon** [comment] 2020-03-30 12:27
My colleague @AdamFloyd (professional designer working in medical/PPE) has designed this low cost visor

@amcewen ?

![image](https://user-images.githubusercontent.com/1537834/77911308-81fa3a80-7288-11ea-8cd0-2efe532d8c97.png)

![image](https://user-images.githubusercontent.com/1537834/77911321-8a527580-7288-11ea-9a10-da2c039788dc.png)

![image](https://user-images.githubusercontent.com/1537834/77912131-e964ba00-7289-11ea-8be7-afdd52fdff32.png)

![image](https://user-images.githubusercontent.com/1537834/77912156-f1245e80-7289-11ea-9038-4f0299d11823.png)

![image](https://user-images.githubusercontent.com/1537834/77912166-f7b2d600-7289-11ea-8404-0620542c9a28.png)

![image](https://user-images.githubusercontent.com/1537834/77912184-000b1100-728a-11ea-8cd2-07ab46fcc981.png)

![image](https://user-images.githubusercontent.com/1537834/77912198-07321f00-728a-11ea-9f48-80e263b17db5.png)

![image](https://user-images.githubusercontent.com/1537834/77912213-1022f080-728a-11ea-97d0-db331b174c2f.png)

![image](https://user-images.githubusercontent.com/1537834/77912229-16b16800-728a-11ea-8bc4-7d4493202104.png)

**Comment by KarlDunkerley** [comment] 2020-03-30 13:30
Can you send him a pic of mine?

Just been into town to get staples, stapler, strimmer, nail clippers and 4 Hole Punch. If anyone from near southport heading into Does they can take the latter with them. Don't need it for my design but thought Ade and 3Ders might need it.
WHSmith and Boots very useful today.




    On Monday, 30 March 2020, 13:27:34 BST, Alex Lennon <notifications@github.com> wrote:  
 
 


My colleague @AdamFloyd (professional designer working in medical/PPE) has designed this low cost visor

@amcewen ?

**Comment by KarlDunkerley** [comment] 2020-03-30 13:50
A Spanish idea for ventilators out of 3D... https://www.bbc.co.uk/news/av/technology-52072479/a-3d-printed-ventilator-designed-for-spain-s-coronavirus-patients

**Comment by JamieJ90** [comment] 2020-03-31 19:13
Hi, 
I have had a look at the Prusa RC3 with top cover design (takes 4 hours 41 mins to print, will print at least 1 for a look)
I know some of the others design print times are around 1:30 - 1:50 (where you can print 2 or 3 off, for every 1 Prusa RC3 with top cover design)

is there a way to make the Prusa RC3 with top cover design thinner so that print time is lower, looks like the hook thing at the back could be lowered and for the height to nearly be half (just an opinion with looking at it in cura)

I am new into 3D printing, so not sure how to it, and if it would be ok

**Comment by KarlDunkerley** [comment] 2020-04-01 12:24
Hand cut corners (several sheets at once) and stapled foam and elastic. 

Takes only seconds to assemble pre-cut pieces. 8 Staples.

Stanley knife if you hand cut the foam strips. Laser them.

Monkeys like me can make these in less than a minute.



![Mk III Stapled 01](https://user-images.githubusercontent.com/34492815/78136793-1ba62100-741c-11ea-84d4-b2da16b51672.jpg)
![Mk III Stapled 02](https://user-images.githubusercontent.com/34492815/78136797-1cd74e00-741c-11ea-9db4-c35a5a03a158.jpg)
![Mk III Stapled 03](https://user-images.githubusercontent.com/34492815/78136798-1cd74e00-741c-11ea-8360-3c2b47eed34b.jpg)

**Comment by markmellors** [comment] 2020-04-06 19:43
Hi all. I'm not sure if this is the best thread to post this in, but thought you'd be interested to know we (Cambridge Makespace and related volunteers) have now got an NHS approved process for producing Delve design visors, and the all documentation neccessary for their approval. The precautions and documentation should be releveant to all visor designs, we've shared all of it. intro here: https://web.makespace.org/visor/  ,  with the docs hosted here: https://github.com/Makespace/visor

**Comment by ajlennon** [comment] 2020-04-06 20:34
Hi @markmellors - can you give me a quick synopsis:

- are any of the materials difficult to source
- is any machinery needed (3D printing, Laser cutting) of can this be done by an team of volunteers with scissors?

Thanks!

**Comment by markmellors** [comment] 2020-04-06 20:45
Its the delve design, no changes to materials or assembly process. only change to what we do to the materials is cleaning them. Oh and we wrap the elastic around the PET so it gets stapled twice, but I don't think that's strictly neccessary. And we put a sticker on them with contact details (PPE regs).

It could be done using only a pair of scissors (plus cleaning materials and PPE), but a laser cutter (for PET)  and a bandsaw (for foam cutting) make it quicker but are not at all essential.  
materials: 
* 25mm wide elastic (preferably latex free, but we couldn't source that so have a sticker on the bag with a warning
* ~0.2mm PET
* 25mm self adhesive PU foam
* two regular staples

If you're thinking 'can we scale this to an army of volunteers at home?' - yes you could, but being sure they were following all the procedures would be a nightmare.  It would be easier to forget most of the procedures and just quarantine the stock for a week.

**Comment by ajlennon** [comment] 2020-04-06 20:49
I don't know anything about the delve design I'm afraid @markmellors

>If you're thinking 'can we scale this to an army of volunteers at home?' - yes you could, but being sure they were following all the procedures would be a nightmare. It would be easier to forget most of the procedures and just quarantine the stock for a week.

I am thinking can we get an army of students at > 2m desks in a business space in Liverpool where they can be monitored and have them following the procedures and making these?

**Comment by markmellors** [comment] 2020-04-06 20:55
The delve design is basically the same as in the picture in @KarlDunkerley post above.
https://www.delve.com/insights/face-shield-designs-to-fill-the-gap

You could totally do that. if you do that, you'll want to use the software  @axiomsofchoice  at makespace developed. it tracks lot numbers, materials, who's worked on what, WIP. basically full production tracking software. Every stations has a chromebook with a form that updates a google doc, though I think he's porting it to something thats easier to transfer/setup. 
I think we average about a visor a minute, with a team of 6, though its been getting faster as we've streamlined the process.

**Comment by ajlennon** [comment] 2020-04-06 20:56
Just what I need for #37  Thanks!

**Comment by ajlennon** [comment] 2020-04-06 23:46
OK we have a location. Just need to sort out materials and volunteers! Maybe I can pick your brains tomorrow @markmellors ?

[Edit: Or today even! ]

**Comment by markmellors** [comment] 2020-04-07 08:01
Yeah, no problem

**Comment by axiomsofchoice** [comment] 2020-04-07 13:20
> You could totally do that. if you do that, you'll want to use the software @axiomsofchoice at makespace developed. it tracks lot numbers, materials, who's worked on what, WIP. basically full production tracking software. Every stations has a chromebook with a form that updates a google doc, though I think he's porting it to something thats easier to transfer/setup.

I'm in the process of preparing the code for pushing to this repo: https://github.com/axiomsofchoice/jobcardsystem

**Comment by KarlDunkerley** [comment] 2020-04-07 13:24
TBH 
This is all getting v complicated when i'm trying to churn visors out. 300 over weekend. 100 yesterday. 300 today. 200 tomorrow.
Not sure I can jump through so many hoops.
Karl


    On Tuesday, 7 April 2020, 14:21:04 BST, Dan Hagon <notifications@github.com> wrote:  
 
 



You could totally do that. if you do that, you'll want to use the software @axiomsofchoice at makespace developed. it tracks lot numbers, materials, who's worked on what, WIP. basically full production tracking software. Every stations has a chromebook with a form that updates a google doc, though I think he's porting it to something thats easier to transfer/setup.


I'm in the process of preparing the code for pushing to this repo: https://github.com/axiomsofchoice/jobcardsystem

**Comment by ajlennon** [comment] 2020-04-07 14:01
>I'm in the process of preparing the code for pushing to this repo: https://github.com/axiomsofchoice/jobcardsystem

Great thanks @axiomsofchoice !

**Comment by amcewen** [comment] 2020-04-29 14:48
Our visor spec is pretty fixed now (9000+ visors in... :-)

**Closed as completed by amcewen** 2020-04-29 14:48 UTC
Labels: help wanted, designs - visors, medical_input
