### ISSUE TITLE
Locate local manufacturing resources we can leverage (3D printers, laser cutters)

### ISSUE THREAD

**Issue by ajlennon** [DoESLiverpool/covid19#31] opened 2020-03-30 21:04 UTC
Have been reaching out to ask if local schools have 3D printers or laser cutters we can borrow.

**Comment by drakard** [comment] 2020-03-30 21:14
I can contribute to this when #28 is resolved.

**Comment by amcewen** [comment] 2020-04-05 09:29
Duplicate of #46 (and that  one has more details on it).

**Closed as completed by amcewen** 2020-04-05 09:29 UTC
Labels: duplicate, help wanted
