### ISSUE TITLE
Develop a clear rota & check-in system(s) - to enable full production with minimum people on-site

### ISSUE THREAD

**Issue by afroleft** [DoESLiverpool/covid19#69] opened 2020-04-12 12:18 UTC
Excellent work whoever kicked off the Rota  [Link](https://docs.google.com/spreadsheets/d/1Nn2kCCu9TOgxJlUh01Y-L10jXJNEoijAkrV9hTZMpOo/edit?usp=sharing) 

@plastictactics over in #47 

> The discoverability of the rota was not very good so I've updated the readme.md on the homepage. I think it's essential that everyone is aware of and using the rota to avoid too many or too few people coming to the space.

Readme a good idea, we could link up from the landing page too if that helps.

Questions about the Rota:
* Can I start pointing those that are reaching out over the website to volunteer? [Link](https://github.com/DoESLiverpool/covid19/issues/47#issuecomment-612421041) 
* It looks a bit empty, Is everyone using this as their source of truth? 

> I think it's essential that everyone is aware of and using the rota to avoid too many or too few people coming to the space.

Agreed, does this Rota roster an appropriate number of people?

**Comment by JackiePease** [comment] 2020-04-12 13:06
It does, we should definitely use it. I've updated that link to point to the manufacturing document (which references the rota). 
I think @amcewen is still looking over it, but I think that's the right place to point new volunteers.
Current intention is to email the DoES community and social media later today to get more volunteers.

**Comment by MatthewCroughan** [comment] 2020-04-13 11:12
https://github.com/DoESLiverpool/covid19/issues/74 has been spun up by Julian. I think that using a spreadsheet is the wrong approach and we need to change to a simple calendar, so that people can simply say that they're going to be in the space at a certain time, and conflicts can be easily seen. 

![image](https://user-images.githubusercontent.com/26458780/79115486-d8ce3c80-7d7d-11ea-9025-c0676889cc37.png)
![image](https://user-images.githubusercontent.com/26458780/79116853-7119f080-7d81-11ea-855c-e2c48c72aec9.png)


[A link to add this calendar to your google account, where you can add to it](https://calendar.google.com/calendar/b/1?cid=dDhudXZtM3IyMGs5NHVxM2FnZnRkN3RsdGNAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ)

[A link to publicly see the spreadsheet without a google account](https://calendar.google.com/calendar/embed?src=t8nuvm3r20k94uq3agftd7tltc%40group.calendar.google.com&ctz=Europe%2FLondon)

**Comment by JackiePease** [comment] 2020-04-13 12:03
I thought there was a majority who thought that the spreadsheet was clearer.

**Comment by Robotorium** [comment] 2020-04-13 12:08
I'm honestly not sure why this is still being discussed. It's not about having the best, most amazing workflow possible. It's about getting the work done.

Whatever solution will make this stop taking up time and energy, please. Just get the visors made.

**Comment by ajlennon** [comment] 2020-04-13 12:13
> I'm honestly not sure why this is still being discussed. It's not about having the best, most amazing workflow possible. It's about getting the work done.
> 
> Whatever solution will make this stop taking up time and energy, please. Just get the visors made.

^^^ this. Let's #GetItDone

**Comment by plastictactics** [comment] 2020-04-14 10:16
@afroleft 's first question seems to have been answered in the affirmative:

> Can I start pointing those that are reaching out over the website to volunteer? 

But the other two seem worth exploring before we close this issue:

> It looks a bit empty, Is everyone using this as their source of truth?
> does this Rota roster an appropriate number of people?

The spreadsheet solution is gaining inertia as the one source of truth, so would need increasingly strong reasons to switch to calendar at this stage which I don't think are there. From what I've seen the sheet is not perfect but working well enough to keep production going. With apologies to @MatthewCroughan :)

Can someone in the space today assess how the people in the space now match up with the spreadsheet? According to the sheet, only Freddie L is in the space until 1pm. Either there are undocumented people (papers please) or we're operating at 1/3 production.

**Comment by goatchurchprime** [comment] 2020-04-14 12:47
Please don't misconstrue my use of the spreadsheet to run the rota as preference/inertia for it over using the calendar.  This is the source of group-think, when everyone assumes everyone else prefers the current state of affairs, because it seems they are getting along with it.  Calendars have all sorts of material productivity features, like hooking in with automated text-reminders to remind you to get to work on time while you're engrossed in digging in the garden.  You don't get that or other time-management domain features from a spreadsheet.

The way to settle the issue is to set up a poll and count the votes, rather than make assumptions. 

Likewise, some kind of check-in/check-out system can be crucial (issue #74) because we know that what is written in the spreadsheet/calendar is not at all the same as what is happening in the real world.  This matters, because I live 10 minutes away by bike, and can hop over if it looks like there is low staffing in the cleaning station, but I don't want to turn up -- as I have done several times -- when all stations are already busy. This should not be a big deal, as most work plants have check-in books, even when they don't need them.  At the moment, my only option (after enough wasted journeys) is to phone up and ask who is there verbally, which I am sure wastes more of people's time than it would be to update a check-in/check-out page on a public computer.

**Comment by plastictactics** [comment] 2020-04-14 14:00
All very good points. I second your suggestion from #74 of having a check-in/check-out document for use on entry/exit - a trial sounds great to me.

I have been pruning issues to try and increase engagement with the board. I might have misjudged by merging these two - but can see a use case where someone checks the live check in, decides to come in, then someone else arrives at the same time for the rota slot which was ten minutes later. If the two systems can be integrated that would have some benefits.

My view is that none of the solutions are developed enough to vote on yet. A design brief might help get us all on the same page and reduce assumptions. At a minimum it makes it clearer in my own mind. Just a starting point based on what I've read on this board - amendments/rewrites welcome:

**Rota**
- Enables inducted people to mark their intent in blocks of time (standard duration, e.g. 2 hrs, or flexible?)
- Makes double-booking unlikely
- Provides for new volunteers who need to be inducted to be matched with 'inducters'
- Sends reminders to individuals who have marked their name x minutes before the start time (?)
- Enables 'management' to scan the days ahead so they can put out a call for volunteers for upcoming gaps

**Live check-in**
- Records in real-time the people in the space
- Allows people off-site to see who is in the space and what they are working on
- Allows users to set intent that they will shortly be in the space (?)

**Both**
- Maximise production
- Minimise people visiting the space speculatively and wasted trips
- Clearly signposted (e.g. in readme.md and website)
- Require low management overhead and checking
- Accessible for volunteers with low tech literacy (?)
- Accessible without login from mobile web browser (?)

**Comment by dfaligertwood** [comment] 2020-04-14 15:11
> Can someone in the space today assess how the people in the space now match up with the spreadsheet? According to the sheet, only Freddie L is in the space until 1pm. Either there are undocumented people (papers please) or we're operating at 1/3 production.

This was correct. But its a bit disingenuous to say 1/3 production - more people can do cleaning simultaneously than laser cutting, so its less important to get them to be in the space continually.

From having actually done the checkin/checkout thing today, a dropdown and button google form would be easier than going through the spreadsheet, and not too hard to make for someone with google docs access. Signposting on the website to the spreadsheet could be better though - I think it is now completely absent?

**Comment by plastictactics** [comment] 2020-04-14 15:20
I have considered winding my neck in on this as I haven't visited the space in a good few days now - so not aware of how recent production is happening or any changes to the set up... or able to implement anything on-site 😅 

That said, last time I was in there was just one cleaning station. I can see that multiple stations could be set up to increase capacity in line with social distancing but don't know if this has been set up.

This might sound direct but tone is supposed to be curious - where would you expect to find links to the spreadsheet, or where might it be so that people can find it quickly? We can make a request to add them.

**Comment by JackiePease** [comment] 2020-04-14 15:33
The cleaning station actually takes up a lot of space, so with the 2m rule, and trying to avoid surfaces that might get damaged, it's difficult to see how we could have multiples. We've been experimenting with sending the bands to be cleaned and packed at home - this might be a solution giveb good instruction and supervision.

Also it's the sort of task which works well with 2 people doing it, ok for 2 people from the same household - may be worth mentioning this in the document.
________________________________

**Comment by dfaligertwood** [comment] 2020-04-14 15:33
There is currently just one cleaning station, just observing that it is _possible_ to parallelise that - either with more onsite cleaning or with home work - whereas less is possible with the laser cutter.

I'd expect to find links in either the covid19 readme, the covid19/visor-designs/laser-cut readme or production.md in the same. It was in one of them (I forget which - maybe production.md?) but has been removed, so I didn't want to steamroller in and re-add it for no reason.

**Comment by dfaligertwood** [comment] 2020-04-14 15:38
It was production.md, loads got stripped out in 9596779 it looks like by accident, so I'll just put in a pull req now.

**Comment by plastictactics** [comment] 2020-04-14 15:41
Nice one @dfaligertwood.

This home-cleaning stuff is interesting - first I've heard of it. I can find more volunteers to do this if asked. Being able to clean and pack all the visors off-site of the space would cut a huge amount of visits (and visits = risk).

**Comment by drakard** [comment] 2020-04-14 16:20
I heard the rota isn't full tomorrow. I can come in in the afternoon. The spreadsheet has changed since I last used it. "cutting bands" does that mean operating the laser cutter?

**Comment by JackiePease** [comment] 2020-04-14 18:24
@drakard  - yes it does. We realised the machine minding row was causing confusion (it was for a 3d printer set up that didn't work out)

**Comment by ajlennon** [comment] 2020-04-14 18:39
HI @JackiePease - what rota page should I be using now? Thanks!

**Comment by dfaligertwood** [comment] 2020-04-14 22:17
Just ftr I made the pull request with rota links etc (#80) so if someone could check it over that would be great 👍

**Comment by plastictactics** [comment] 2020-04-15 13:36
The check in page had become unusable due to some additional rows with large height added above the frozen headings - I've made them more compact so most browsers should be able to see the content.

It would be good to know who is amending the sheet and to what end, as it looks to me like a duplication of the rota on the first tab of the spreadsheet. [(link again for reference)](https://docs.google.com/spreadsheets/d/1Nn2kCCu9TOgxJlUh01Y-L10jXJNEoijAkrV9hTZMpOo/edit#gid=1319346095)

@dfaligertwood Thanks for the correction - have merged it (don't really know what I'm doing on that front but it seems to have worked without breaking anything)

**Comment by drakard** [comment] 2020-04-17 12:12
On the opinion poll page can the author please put a link to the calendar app. I don't think I can evaluate the difference without that.

**Comment by goatchurchprime** [comment] 2020-04-17 12:42
There's the current DoESLiverpool calendar that is used to track events here:  https://doesliverpool.com/calendar/

This pulls in other ones, such as the one Matt made here:

https://calendar.google.com/calendar/embed?src=t8nuvm3r20k94uq3agftd7tltc%40group.calendar.google.com&ctz=Europe%2FLondon

@MatthewCroughan needs to change the setting of it so we can all edit it, just as we do the google docs.  Instructions are here:  https://docs.simplecalendar.io/make-google-calendar-public/

The point is that Jackie could make a laser induction and add me and the student as "guests", and it we'll both get notified after it's checked for clashes.

**Comment by MatthewCroughan** [comment] 2020-04-17 14:19
@goatchurchprime No. You are giving people a read-only link, that is for embedding on webpages and giving people it without giving people access to it.

I already linked to a publicly editable link [in this comment.](https://github.com/DoESLiverpool/covid19/issues/69#issuecomment-612857449)

[Here's the link again. Add this calendar to your google account, where you can add to it](https://calendar.google.com/calendar/b/1?cid=dDhudXZtM3IyMGs5NHVxM2FnZnRkN3RsdGNAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ)

The way you use this is:

1. Click that link
2. Add this calendar to your account, as it asks you to do
3. Add to it

Edit:

It seems actually that the only way one can add people to actually add timeslots is by their email. Everything else is just view only. I'm not sure how the DoES laser cutting bookings work, but that's how we want it to work.
 
![image](https://user-images.githubusercontent.com/26458780/79582071-2ff84800-80c3-11ea-8775-104c94959216.png)

**Comment by amcewen** [comment] 2020-04-17 14:47
/me looks through to the main room where an assortment of volunteers have been happily working on things all week and using the spreadsheet to coordinate that.

We have a spreadsheet, it's working reasonably well.  I'd expect any problems in people not filling it in and just turning up would also be the case with a calendar, and so the calendar wouldn't massively improve matters.  And there's now a reasonably large cost of switching and informing/retraining everyone who has been using the spreadsheet, so we're **sticking with the spreadsheet**.

**Closed as completed by amcewen** 2020-04-17 14:47 UTC
Labels: question, production
