### ISSUE TITLE
Gerald Dropping power

### ISSUE THREAD

**Issue by jadenoon** [DoESLiverpool/covid19#111] opened 2021-05-24 06:23 UTC
Gerald is dropping power going towards the centre and to the right when cutting. Cuts fine right in the left hand corner but will not cut through 3mm MDF going towards the right even when speed is reduced down to 8.

**Comment by arthurrowland** [comment] 2021-05-24 09:30
I had some trouble with Gerald on Friday and didn't have time to document it at the time.

Short version:
I think the beam is out of alignment due to a small twist in the gantry caused by the right-hand y-axis belt tension, after I tried to fix it. So adjusting the mirror alone would not resolve it.

Full version:
On Friday morning I let the laser hit the y-axis limit at the back of the bed. Towards the end of the next cut I was getting a split beam effect with burnt shadows around the cut, and very low power. I then noticed the right hand y-axis belt was very slack (resting on the surface below) and that the clip had come loose and was missing a nut. I tightened the belt back up, replaced the M3 nut (the original must have fallen down the back) and realigned the mirror on the left with the help of @amcewen. It seemed to be cutting well (sharp and full power) in the afternoon but there was a drop off towards the right of the bed. We didn't know how to fit the belts to get it reliably orthogonal (had to use spell check on that word) so I think there's still a twist, causing the loss of focus / drop in power.

Paging @DoESLiverpool/laser-maintenance via @magman2112 (I don't think I can tag the former in this covid-19 repo).

**Comment by amcewen** [comment] 2021-05-24 09:39
@magman2112 adjusted the belt tension on Saturday which (I believe) fixed the skew in cutting, but maybe the alignment still isn't spot on?

**Comment by magman2112** [comment] 2021-05-24 10:15
It took a couple of attempts, but I sorted out the left hand belt tensioner on Saturday and also corrected the squareness of the horizontal beam (it was out by approx 10mm across the bed).

I did also check the alignment of the laser, as it was well out, but I on,y did this quickly, as @JackiePease and I were conducting a laser training session at the time.

It will likely be tomorrow before I can come in and check the alignment on Gerald though.

**Comment by arthurrowland** [comment] 2021-05-24 15:36
Brett cleaned the mirrors this morning and reports it is working well now.

**Comment by JackiePease** [comment] 2021-05-25 11:51
Closing this as @arthurrowland has added now a link in https://github.com/DoESLiverpool/somebody-should/issues/1543

**Closed as completed by JackiePease** 2021-05-25 11:51 UTC

**Comment by jadenoon** [comment] 2021-05-25 12:28
Ahh great! Glad to here!

Sent from my iPhone

On 25 May 2021, at 12:51, Jackie Pease ***@***.***> wrote:

﻿

Closing this as @arthurrowland<https://github.com/arthurrowland> has added now a link in DoESLiverpool/somebody-should#1543<https://github.com/DoESLiverpool/somebody-should/issues/1543>
